### ISSUE TITLE
Support of Bouncy Castle JCE is not implementing yet

### ISSUE THREAD

**Issue by unikulin** [awslabs/aws-encryption-sdk-java#15]
looks like here is chipper from Java JCE only not from BC JCE.
How I can use Cipher from BC?
aws-encryption-sdk-java/src/main/java/com/amazonaws/encryptionsdk/internal/CipherHandler.java
private static Cipher buildCipherObject(final CryptoAlgorithm alg) {
        try {
            // Right now, just GCM is supported
            return Cipher.getInstance("AES/GCM/NoPadding");
        } catch (final GeneralSecurityException ex) {
            throw new IllegalStateException("Java does not support the requested algorithm", ex);
        }
    }

**Comment by SalusaSecondus** [comment]
Are you concerned that the AES-GCM implementation may not come from BouncyCastle but rather from Java's default provider? It is a perfectly acceptable implementation. We need to use BouncyCastle for RSA OAEP SHA-256 and ECDSA due to bugs or limited functionality in the default Java implementations, but for everything else, Java's defaults work just fine.

If you want to force BouncyCastle to be used for cryptography throughout your application, you should install it as your highest priority provider. This can be done using [Security.insertProviderAt(int)](https://docs.oracle.com/javase/8/docs/api/java/security/Security.html#insertProviderAt-java.security.Provider-int-).

**Comment by unikulin** [comment]
Thanks
