### ISSUE TITLE
Expose additional information for metrics

### ISSUE THREAD

**Issue by DarrellMozingo** [awslabs/aws-encryption-sdk-java#36]
Specifically timing & encrypt/decrypt success/failure rates when using multiple KMS providers that may be skipped over automatically during each operation.

This will help from an operations standpoint when latency spikes up or debugging if we're seeing increased failures.

Unfortunately I'm not terribly sure how this would look with the `DefaultCryptoMaterialsManager` in practice. Callbacks you can register?

As an example, we wrote our own multi-region encryption materials manager and we've tried to add these metrics tagged with the region we're going to. Since we're using a key alias, we can parse the region out of the provider information string easily enough when it's successful (exactly like you do in the `KmsMasterKeyProvider`), but getting the region from `AwsCryptoException` (for encryption errors) or `AWSKMSException` (for data key generation errors) has proven to be a painful parsing exercise :)  Having the region easily accessible on each exception would be quite helpful for this purpose.

Thanks!

**Comment by bdonlan** [comment]
The best way to do this would probably be to add request handlers to the underlying KMS clients themselves - since there needs to be a separate KMS client for each region, you'd know the region based on the client in use. This does require using the builder API for constructing the KMS client (via `AWSKMSClientBuilder.withRequestHandlers`), which we don't yet support - but I just submitted a PR (#40) to add support for builder-style KMS client construction.

**Comment by DarrellMozingo** [comment]
That's perfect! :+1:  Didn't realise the SDK had a request handler we could tie into. Thanks for the suggestion and getting it worked into the encryption SDK so quickly. I'll keep an eye out for the new release when that PR is merged in.
