### ISSUE TITLE
crypting Kinesis record for .NET

### ISSUE THREAD

**Issue by jdkorigan** [awslabs/aws-encryption-sdk-java#52]
Hi,
I contacted AWS support and they told me you could maybe help. If I'm at the wrong location just tell me where to post this message. 
I'm looking for .Net encryption library for Kinesis' PutRecord/PutRecords. Would you have any idea how to get information for creation of such a library ?
Thank you

**Comment by mattsb42-aws** [comment]
Kinesis just deals in arbitrary blobs of data, so no special formatting would be necessary for performing client-side encryption of data passed over Kinesis.

The AWS Encryption SDK format and framework offer valuable characteristics that would benefit you in such a use case, as we show in our example[1], but unfortunately we do not have a .NET client available at this time. It is on our roadmap but we do not have a timeline for it.

While you would not have the benefits of the AWS Encryption SDK, you could definitely use another encryption format that is already supported by tooling in your language of choice. You will, however, need to be sure that the tooling you are using makes secure decisions regarding algorithms, key handling, IVs, and the like.

For reference (since we do not currently have a .NET option), some of the major valuable characteristics that the AWS Encryption SDK would provide in cases like this include:
* Safe and automatic selection of encryption and signing algorithms
* Ciphertext portability
* Ciphertext interoperability with other languages
* Ease of use
* Safe and easy configuration of data key reuse

[1] https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/sample-cache-example.html

**Comment by mattsb42-aws** [comment]
Closing as this question appears to have been answered. Feel free to open the issue again if there are more questions around this.
