### ISSUE TITLE
Library performance

### ISSUE THREAD

**Issue by ngbalk** [awslabs/aws-encryption-sdk-java#54]
How much of a performance impact is there (if any at all) to doing AES-GCM encryption with generating a new data key for each encryption operation VS other modes of encryption where we wouldn't generate a new data key for each encryption operation?  Have any benchmarks of this library vs other libraries been published?

**Comment by mattsb42-aws** [comment]
The algorithm and mode used and data key management are not really directly related. We use GCM because it is more secure than other AES modes as a result of it providing ciphertext integrity and authenticity controls in addition to the confidentiality controls that other modes provide.

We do support data key reuse, but it is important to note that there are security trade offs any time you reuse a data key across multiple messages. Additionally, the performance gains that you get from data key reuse have nothing to do with the actual encryption operations and everything to do with interacting with your master key. We talk at much greater length about this compromise in this blog post[1].

We do not have any performance benchmarks at this time. However, as a general principal, I would recommend looking first at what security characteristics you are trying to achieve, then determine what sort of performance is reasonable when achieving the security you need (ie: security first, then performance). Any encryption will always add performance overhead versus handling plaintext: the question is whether that overhead actually affects you at all (depending on your use case it might be negligible) and what costs (in time, resources, money, etc) you are willing to pay to obtain the security characteristics that you need/want.

[1] https://aws.amazon.com/blogs/security/aws-encryption-sdk-how-to-decide-if-data-key-caching-is-right-for-your-application/
